/**
 * ============================================================================
 * NKTg AI SYSTEM - LANGUAGE MODULE (UI chrome i18n — KHÔNG đụng nội dung output)
 * ============================================================================
 * Dịch giao diện (nhãn nút, placeholder, tiêu đề, thông báo trạng thái ngoài
 * khung Log) sang 8 ngôn ngữ, giống bộ ngôn ngữ đã có sẵn ở Guide.
 *
 * KHÔNG liên quan tới:
 *   - Khung "NKTg Core Kernel Output Log" (Logger.log trong mọi step)
 *   - BAR_CHART_TEXT / FALLBACK_TEXT trong step8-output-layer*.js — đó là
 *     ngôn ngữ tự nhận diện theo VĂN BẢN ĐẦU VÀO (Step 2), khác bản chất
 *     hoàn toàn với lựa chọn ngôn ngữ GIAO DIỆN ở đây.
 *
 * Quy ước: dùng chung window.* với auth.js / history-manager.js / settings.js.
 */

const LANG_STORAGE_KEY = 'nktg_ui_lang';
const DEFAULT_LANG = 'EN';

// Trùng danh sách + cờ với Guide để nhất quán toàn app
export const LANGS = {
    EN: { flag: '🇺🇸', label: 'English' },
    VI: { flag: '🇻🇳', label: 'Tiếng Việt' },
    FR: { flag: '🇫🇷', label: 'Français' },
    DE: { flag: '🇩🇪', label: 'Deutsch' },
    ES: { flag: '🇪🇸', label: 'Español' },
    ZH: { flag: '🇨🇳', label: '中文' },
    JA: { flag: '🇯🇵', label: '日本語' },
    RU: { flag: '🇷🇺', label: 'Русский' },
};

// ============================================================================
// TỪ ĐIỂN — flat key, dùng chung 1 cấp (không nested) cho dễ tra cứu
// ============================================================================
const TRANSLATIONS = {
    EN: {
        'nav.newChat': 'New chat',
        'nav.guide': 'Guide',
        'nav.signup': 'Sign Up / Log in',
        'nav.history': 'History',
        'history.empty': 'No history yet',
        'history.loginToView': 'Log in to view history',
        'history.shareConversation': 'Share conversation',
        'history.unpin': 'Unpin',
        'history.pin': 'Pin',
        'history.rename': 'Rename',
        'history.delete': 'Delete',
        'history.renamePlaceholder': 'Enter new name...',
        'history.shareLinkDesc': 'Public link you can share',
        'history.copy': 'Copy',
        'history.copied': '✓ Copied',
        'history.shareSocial': 'Share to social media',
        'history.deleteConfirm': 'Delete this item from history?',
        'history.pinnedTooltip': 'Pinned',
        'history.optionsTooltip': 'Options',
        'history.clearAll': '🗑 Clear all history',
        'history.clearAllConfirm': 'Clear all history?',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ Please select Extraction or Addition before running the pipeline.',
        'charLimit.warning': '⚠ Character limit exceeded (21000)',
        'queryInput.placeholder': 'Enter text or click [+] to attach files (.txt, .docx, .pdf, .png, .jpg, .webp)...',
        'auth.title': 'NKTg Account',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'Email',
        'auth.passwordPlaceholder': 'Password',
        'auth.loginBtn': 'Log in',
        'auth.noAccount': "Don't have an account?",
        'auth.registerNow': 'Sign up now',
        'auth.fullNamePlaceholder': 'Full name',
        'auth.passwordMinPlaceholder': 'Password (min. 6 characters)',
        'auth.confirmPasswordPlaceholder': 'Confirm password',
        'auth.registerBtn': 'Create account',
        'auth.haveAccount': 'Already have an account?',
        'auth.loginNow': 'Log in',
        'settings.title': 'Settings',
        'settings.gearTitle': 'Settings',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': 'You are not logged in.',
        'account.login': 'Log in',
        'account.logout': 'Log out',
        'account.logoutConfirm': 'Do you want to log out?',
        'account.changePwd': 'Change password',
        'account.currentPwdPlaceholder': 'Current password',
        'account.newPwdPlaceholder': 'New password (min. 6 characters)',
        'account.confirmNewPwdPlaceholder': 'Confirm new password',
        'account.save': 'Save',
        'account.cancel': 'Cancel',
        'account.pwdMismatch': 'Password confirmation does not match.',
        'account.deleteAccount': 'Delete account',
        'account.deleteWarning': 'This will permanently delete your account and all history <strong>on this browser</strong>. This cannot be undone.',
        'account.deletePwdPlaceholder': 'Enter your password to confirm',
        'account.deletePermanently': 'Delete permanently',
        'account.deleteWrongPwd': 'Incorrect password.',
        'account.deleteConfirmGoogle': 'Permanently delete this account from this browser? All history will be deleted and cannot be undone.',
        'changePwd.onlyEmail': 'Only available for Email accounts.',
        'changePwd.wrongCurrent': 'Current password is incorrect.',
        'changePwd.tooShort': 'New password must be at least 6 characters.',
        'changePwd.success': 'Password changed successfully!',
        'plan.free': 'Free',
        'plan.licenseKey': 'License Key',
        'plan.licensePlaceholder': 'Paste your license key after purchase...',
        'plan.licenseDisabled': 'Not available yet — store activation pending',
        'plan.activate': 'Activate',
        'plan.activating': 'Activating...',
        'plan.activateSuccess': 'Activated successfully!',
        'plan.activateInvalid': 'Invalid license key.',
        'plan.activateError': 'Connection error — please try again.',
        'general.profile': 'Profile',
        'general.fullName': 'Full name',
        'general.preferredName': 'What should NKTg AI call you?',
        'general.preferredNamePlaceholder': 'e.g. a nickname...',
        'general.saved': 'Saved',
        'general.avatarChange': 'Change avatar',
        'general.avatarRemove': 'Remove avatar',
        'general.avatarError': "Couldn't upload this image, please try another.",
        'common.close': 'Close',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — ready',
        'inputAdapter.success': '✔ {name} — {chars} chars',
        'inputAdapter.unsupportedFormat': 'Unsupported file format: .{ext}. Only .txt, .docx, .pdf, .png, .jpg, .webp, .bmp are accepted.',
        'inputAdapter.emptyContent': '{name}: Empty content after extraction.',
        'inputAdapter.exceedsLimit': '{name}: Exceeds {max} characters (current: {current}). Please shorten the content.',
        'inputAdapter.cannotReadTxt': 'Cannot read .txt file',
        'inputAdapter.cannotReadDocx': 'Cannot read .docx file',
        'inputAdapter.cannotReadPdf': 'Cannot read .pdf file',
        'inputAdapter.mammothError': 'Word document processing error: {msg}',
        'inputAdapter.pdfError': 'PDF processing error: {msg}',
        'inputAdapter.canvasResizeFailed': 'Image resize failed',
        'inputAdapter.cannotLoadImage': 'Cannot load image for resize',
        'inputAdapter.ocrLoadFailed': 'Text recognition engine failed to load',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': 'Analysis',
        'step8.compression': 'Compression',
        'step8.expansion': 'Expansion',
        'step8.chars': 'Chars',
        'step8.copy': '⎘ Copy',
        'step8.copied': '✓ Copied',
        'step8.copyTitle': 'Copy result',
        'step8.condensedTitle': 'Run one more compression round',
        'step8.essenceTitle': 'Deep compress 4 more rounds (5 total)',
        'step8.top': '↑ Top',
        'step8.topTitle': 'Scroll to top',
        'step8.proportionAxis': 'Proportion (%)',
        'step8.dominanceThreshold': 'Dominance Threshold',
        'step8.textStructure': 'Text Structure (100%)',
        'step8.generalFormula': 'General Formula: AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} inputs/day',
        'plan.unlimited': 'Unlimited',
        'plan.usageToday': 'Today: {count}/{limit}',
        'plan.currentBadge': 'Current',
        'plan.comingSoon': 'Coming soon',
        'plan.limitReached': "You've reached today's input limit.",
        'plan.upgradeNow': 'Upgrade',
        'vietqr.buyButton': 'Pay via VietQR',
        'vietqr.title': 'Pay via VietQR',
        'vietqr.creatingOrder': 'Creating order...',
        'vietqr.transferContent': 'Transfer content (keep exactly as shown):',
        'vietqr.waiting': 'Waiting for payment...',
        'vietqr.success': '✓ Payment successful — activated!',
        'vietqr.error': 'Something went wrong. Please try again.',
        'plan.expiresOn': 'Renews/expires: {date}',
        'manual.title': 'Ручная оплата',
        'manual.desc': 'Прямой перевод, отправьте подтверждение оплаты по электронной почте, чтобы получить лицензионный ключ',
        'manual.accountName': 'Владелец счёта',
        'manual.accountNo': 'Номер счёта',
        'manual.bank': 'Банк',
        'manual.instructions': 'После перевода отправьте скриншот транзакции вместе с адресом электронной почты, использованным при регистрации, на:',
        'manual.note': 'Ваш лицензионный ключ будет отправлен по электронной почте — 50 000 VND = Plus, 125 000 VND = Pro',
        'manual.title': '手動決済',
        'manual.desc': '直接振込み、支払い証明をメールで送ってライセンスキーを受け取る',
        'manual.accountName': '口座名義',
        'manual.accountNo': '口座番号',
        'manual.bank': '銀行',
        'manual.instructions': '振込み後、取引のスクリーンショットと登録に使用したメールアドレスを以下に送信してください：',
        'manual.note': 'ライセンスキーはメールで送付されます — 50,000 VND = Plus、125,000 VND = Pro',
        'manual.title': '手动支付',
        'manual.desc': '直接转账，通过电子邮件发送付款凭证以获取许可证密钥',
        'manual.accountName': '账户持有人',
        'manual.accountNo': '账号',
        'manual.bank': '银行',
        'manual.instructions': '转账后，请将交易截图和您注册时使用的邮箱发送至：',
        'manual.note': '许可证密钥将通过电子邮件发送 — 50,000 VND = Plus，125,000 VND = Pro',
        'manual.title': 'Pago manual',
        'manual.desc': 'Transferencia directa, envía tu comprobante de pago por correo para recibir una clave de licencia',
        'manual.accountName': 'Titular de la cuenta',
        'manual.accountNo': 'Número de cuenta',
        'manual.bank': 'Banco',
        'manual.instructions': 'Después de transferir, envía una captura de la transacción junto con el correo que usaste para registrarte a:',
        'manual.note': 'Tu clave de licencia se enviará por correo — 50.000 VND = Plus, 125.000 VND = Pro',
        'manual.title': 'Manuelle Zahlung',
        'manual.desc': 'Direkte Überweisung, senden Sie Ihren Zahlungsnachweis per E-Mail, um einen Lizenzschlüssel zu erhalten',
        'manual.accountName': 'Kontoinhaber',
        'manual.accountNo': 'Kontonummer',
        'manual.bank': 'Bank',
        'manual.instructions': 'Senden Sie nach der Überweisung einen Screenshot der Transaktion zusammen mit der bei der Anmeldung verwendeten E-Mail-Adresse an:',
        'manual.note': 'Ihr Lizenzschlüssel wird Ihnen per E-Mail zugesandt — 50.000 VND = Plus, 125.000 VND = Pro',
        'manual.title': 'Paiement manuel',
        'manual.desc': 'Virement direct, envoyez votre preuve de paiement par e-mail pour recevoir une clé de licence',
        'manual.accountName': 'Titulaire du compte',
        'manual.accountNo': 'Numéro de compte',
        'manual.bank': 'Banque',
        'manual.instructions': 'Après le virement, envoyez une capture d\'écran de la transaction ainsi que l\'e-mail utilisé pour votre inscription à :',
        'manual.note': 'Votre clé de licence vous sera envoyée par e-mail — 50 000 VND = Plus, 125 000 VND = Pro',
        'manual.title': 'Thanh toán thủ công',
        'manual.desc': 'Chuyển khoản trực tiếp, gửi bằng chứng qua email để nhận License Key',
        'manual.accountName': 'Chủ tài khoản',
        'manual.accountNo': 'Số tài khoản',
        'manual.bank': 'Ngân hàng',
        'manual.instructions': 'Sau khi chuyển khoản, gửi ảnh chụp giao dịch kèm email bạn dùng đăng ký trong app tới:',
        'manual.note': 'License Key sẽ được gửi qua email — 50.000 VND = Plus, 125.000 VND = Pro',
        'manual.title': 'Manual Payment',
        'manual.desc': 'Transfer directly and email your proof of payment to receive a License Key',
        'manual.accountName': 'Account holder',
        'manual.accountNo': 'Account number',
        'manual.bank': 'Bank',
        'manual.instructions': 'After transferring, email a screenshot of the transaction along with the email you used to sign up to:',
        'manual.note': 'Your License Key will be emailed to you — 50,000 VND = Plus, 125,000 VND = Pro',
    },

    VI: {
        'nav.newChat': 'Đoạn chat mới',
        'nav.guide': 'Hướng dẫn',
        'nav.signup': 'Đăng ký / Đăng nhập',
        'nav.history': 'Lịch sử',
        'history.empty': 'Chưa có lịch sử nào',
        'history.loginToView': 'Đăng nhập để xem lịch sử',
        'history.shareConversation': 'Chia sẻ cuộc trò chuyện',
        'history.unpin': 'Bỏ ghim',
        'history.pin': 'Ghim',
        'history.rename': 'Đổi tên',
        'history.delete': 'Xoá',
        'history.renamePlaceholder': 'Nhập tên mới...',
        'history.shareLinkDesc': 'Đường liên kết công khai có thể chia sẻ',
        'history.copy': 'Sao chép',
        'history.copied': '✓ Đã sao chép',
        'history.shareSocial': 'Chia sẻ lên mạng xã hội',
        'history.deleteConfirm': 'Xoá mục này khỏi lịch sử?',
        'history.pinnedTooltip': 'Đã ghim',
        'history.optionsTooltip': 'Tuỳ chọn',
        'history.clearAll': '🗑 Xóa tất cả lịch sử',
        'history.clearAllConfirm': 'Xóa toàn bộ lịch sử?',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ Vui lòng chọn Extraction hoặc Addition trước khi chạy.',
        'charLimit.warning': '⚠ Đã vượt giới hạn 21000 ký tự',
        'queryInput.placeholder': 'Nhập văn bản hoặc bấm [+] để đính kèm file (.txt, .docx, .pdf, .png, .jpg, .webp)...',
        'auth.title': 'Tài khoản NKTg',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'Email',
        'auth.passwordPlaceholder': 'Mật khẩu',
        'auth.loginBtn': 'Đăng nhập',
        'auth.noAccount': 'Chưa có tài khoản?',
        'auth.registerNow': 'Đăng ký ngay',
        'auth.fullNamePlaceholder': 'Họ và tên',
        'auth.passwordMinPlaceholder': 'Mật khẩu (tối thiểu 6 ký tự)',
        'auth.confirmPasswordPlaceholder': 'Xác nhận mật khẩu',
        'auth.registerBtn': 'Tạo tài khoản',
        'auth.haveAccount': 'Đã có tài khoản?',
        'auth.loginNow': 'Đăng nhập',
        'settings.title': 'Cài đặt',
        'settings.gearTitle': 'Cài đặt',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': 'Bạn chưa đăng nhập.',
        'account.login': 'Đăng nhập',
        'account.logout': 'Đăng xuất',
        'account.logoutConfirm': 'Bạn muốn đăng xuất?',
        'account.changePwd': 'Đổi mật khẩu',
        'account.currentPwdPlaceholder': 'Mật khẩu hiện tại',
        'account.newPwdPlaceholder': 'Mật khẩu mới (tối thiểu 6 ký tự)',
        'account.confirmNewPwdPlaceholder': 'Xác nhận mật khẩu mới',
        'account.save': 'Lưu',
        'account.cancel': 'Huỷ',
        'account.pwdMismatch': 'Mật khẩu xác nhận không khớp.',
        'account.deleteAccount': 'Xóa tài khoản',
        'account.deleteWarning': 'Hành động này xóa vĩnh viễn tài khoản và toàn bộ lịch sử <strong>trên trình duyệt này</strong>. Không thể hoàn tác.',
        'account.deletePwdPlaceholder': 'Nhập mật khẩu để xác nhận',
        'account.deletePermanently': 'Xóa vĩnh viễn',
        'account.deleteWrongPwd': 'Mật khẩu không đúng.',
        'account.deleteConfirmGoogle': 'Xóa vĩnh viễn tài khoản này khỏi trình duyệt này? Toàn bộ lịch sử sẽ bị xóa và không thể hoàn tác.',
        'changePwd.onlyEmail': 'Chỉ áp dụng cho tài khoản đăng nhập bằng Email.',
        'changePwd.wrongCurrent': 'Mật khẩu hiện tại không đúng.',
        'changePwd.tooShort': 'Mật khẩu mới tối thiểu 6 ký tự.',
        'changePwd.success': 'Đổi mật khẩu thành công!',
        'plan.free': 'Free',
        'plan.licenseKey': 'License Key',
        'plan.licensePlaceholder': 'Dán license key sau khi mua...',
        'plan.licenseDisabled': 'Chưa khả dụng — đang chờ kích hoạt cửa hàng',
        'plan.activate': 'Kích hoạt',
        'plan.activating': 'Đang kích hoạt...',
        'plan.activateSuccess': 'Kích hoạt thành công!',
        'plan.activateInvalid': 'License key không hợp lệ.',
        'plan.activateError': 'Lỗi kết nối — vui lòng thử lại.',
        'general.profile': 'Profile',
        'general.fullName': 'Họ và tên',
        'general.preferredName': 'Bạn muốn NKTg AI gọi bạn là gì?',
        'general.preferredNamePlaceholder': 'vd: tên gọi thân mật...',
        'general.saved': 'Đã lưu',
        'general.avatarChange': 'Đổi ảnh đại diện',
        'general.avatarRemove': 'Xóa ảnh đại diện',
        'general.avatarError': 'Không thể tải ảnh này lên, vui lòng thử ảnh khác.',
        'common.close': 'Đóng',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — sẵn sàng',
        'inputAdapter.success': '✔ {name} — {chars} ký tự',
        'inputAdapter.unsupportedFormat': 'Định dạng file không được hỗ trợ: .{ext}. Chỉ chấp nhận .txt, .docx, .pdf, .png, .jpg, .webp, .bmp.',
        'inputAdapter.emptyContent': '{name}: Không có nội dung sau khi trích xuất.',
        'inputAdapter.exceedsLimit': '{name}: Vượt quá {max} ký tự (hiện tại: {current}). Vui lòng rút gọn nội dung.',
        'inputAdapter.cannotReadTxt': 'Không thể đọc file .txt',
        'inputAdapter.cannotReadDocx': 'Không thể đọc file .docx',
        'inputAdapter.cannotReadPdf': 'Không thể đọc file .pdf',
        'inputAdapter.mammothError': 'Lỗi xử lý file Word: {msg}',
        'inputAdapter.pdfError': 'Lỗi xử lý file PDF: {msg}',
        'inputAdapter.canvasResizeFailed': 'Lỗi thu nhỏ ảnh',
        'inputAdapter.cannotLoadImage': 'Không thể tải ảnh để thu nhỏ',
        'inputAdapter.ocrLoadFailed': 'Không thể tải công cụ nhận diện văn bản',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': 'Phân tích',
        'step8.compression': 'Nén',
        'step8.expansion': 'Mở rộng',
        'step8.chars': 'Ký tự',
        'step8.copy': '⎘ Sao chép',
        'step8.copied': '✓ Đã sao chép',
        'step8.copyTitle': 'Sao chép kết quả',
        'step8.condensedTitle': 'Nén thêm 1 vòng',
        'step8.essenceTitle': 'Nén sâu 4 vòng tiếp theo (tổng 5)',
        'step8.top': '↑ Lên đầu',
        'step8.topTitle': 'Lên đầu trang',
        'step8.proportionAxis': 'Tỉ lệ (%)',
        'step8.dominanceThreshold': 'Ngưỡng ưu thế',
        'step8.textStructure': 'Cấu trúc văn bản (100%)',
        'step8.generalFormula': 'Công thức chung: AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} lượt nhập liệu/ngày',
        'plan.unlimited': 'Không giới hạn',
        'plan.usageToday': 'Hôm nay: {count}/{limit}',
        'plan.currentBadge': 'Đang dùng',
        'plan.comingSoon': 'Sắp có',
        'plan.limitReached': 'Bạn đã dùng hết hạn mức nhập liệu hôm nay.',
        'plan.upgradeNow': 'Nâng cấp',
        'vietqr.buyButton': 'Thanh toán qua VietQR',
        'vietqr.title': 'Thanh toán qua VietQR',
        'vietqr.creatingOrder': 'Đang tạo đơn hàng...',
        'vietqr.transferContent': 'Nội dung chuyển khoản (giữ nguyên):',
        'vietqr.waiting': 'Đang chờ thanh toán...',
        'vietqr.success': '✓ Thanh toán thành công — đã kích hoạt!',
        'vietqr.error': 'Có lỗi xảy ra. Vui lòng thử lại.',
        'plan.expiresOn': 'Hết hạn/gia hạn: {date}',
    },

    FR: {
        'nav.newChat': 'Nouvelle discussion',
        'nav.guide': 'Guide',
        'nav.signup': "S'inscrire / Se connecter",
        'nav.history': 'Historique',
        'history.empty': 'Aucun historique',
        'history.loginToView': "Connectez-vous pour voir l'historique",
        'history.shareConversation': 'Partager la conversation',
        'history.unpin': 'Désépingler',
        'history.pin': 'Épingler',
        'history.rename': 'Renommer',
        'history.delete': 'Supprimer',
        'history.renamePlaceholder': 'Entrez un nouveau nom...',
        'history.shareLinkDesc': 'Lien public que vous pouvez partager',
        'history.copy': 'Copier',
        'history.copied': '✓ Copié',
        'history.shareSocial': 'Partager sur les réseaux sociaux',
        'history.deleteConfirm': "Supprimer cet élément de l'historique ?",
        'history.pinnedTooltip': 'Épinglé',
        'history.optionsTooltip': 'Options',
        'history.clearAll': "🗑 Effacer tout l'historique",
        'history.clearAllConfirm': "Effacer tout l'historique ?",
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ Veuillez sélectionner Extraction ou Addition avant de lancer le traitement.',
        'charLimit.warning': '⚠ Limite de 21000 caractères dépassée',
        'queryInput.placeholder': 'Saisissez du texte ou cliquez sur [+] pour joindre un fichier (.txt, .docx, .pdf, .png, .jpg, .webp)...',
        'auth.title': 'Compte NKTg',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'Email',
        'auth.passwordPlaceholder': 'Mot de passe',
        'auth.loginBtn': 'Se connecter',
        'auth.noAccount': "Pas encore de compte ?",
        'auth.registerNow': "S'inscrire maintenant",
        'auth.fullNamePlaceholder': 'Nom complet',
        'auth.passwordMinPlaceholder': 'Mot de passe (6 caractères min.)',
        'auth.confirmPasswordPlaceholder': 'Confirmer le mot de passe',
        'auth.registerBtn': 'Créer un compte',
        'auth.haveAccount': 'Vous avez déjà un compte ?',
        'auth.loginNow': 'Se connecter',
        'settings.title': 'Paramètres',
        'settings.gearTitle': 'Paramètres',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': "Vous n'êtes pas connecté.",
        'account.login': 'Se connecter',
        'account.logout': 'Se déconnecter',
        'account.logoutConfirm': 'Voulez-vous vous déconnecter ?',
        'account.changePwd': 'Changer le mot de passe',
        'account.currentPwdPlaceholder': 'Mot de passe actuel',
        'account.newPwdPlaceholder': 'Nouveau mot de passe (6 caractères min.)',
        'account.confirmNewPwdPlaceholder': 'Confirmer le nouveau mot de passe',
        'account.save': 'Enregistrer',
        'account.cancel': 'Annuler',
        'account.pwdMismatch': 'La confirmation du mot de passe ne correspond pas.',
        'account.deleteAccount': 'Supprimer le compte',
        'account.deleteWarning': "Cette action supprime définitivement votre compte et tout l'historique <strong>sur ce navigateur</strong>. Action irréversible.",
        'account.deletePwdPlaceholder': 'Entrez votre mot de passe pour confirmer',
        'account.deletePermanently': 'Supprimer définitivement',
        'account.deleteWrongPwd': 'Mot de passe incorrect.',
        'account.deleteConfirmGoogle': "Supprimer définitivement ce compte de ce navigateur ? Tout l'historique sera supprimé, action irréversible.",
        'changePwd.onlyEmail': 'Disponible uniquement pour les comptes Email.',
        'changePwd.wrongCurrent': 'Le mot de passe actuel est incorrect.',
        'changePwd.tooShort': 'Le nouveau mot de passe doit contenir au moins 6 caractères.',
        'changePwd.success': 'Mot de passe modifié avec succès !',
        'plan.free': 'Free',
        'plan.licenseKey': 'Clé de licence',
        'plan.licensePlaceholder': 'Collez votre clé de licence après achat...',
        'plan.licenseDisabled': 'Pas encore disponible — activation de la boutique en attente',
        'plan.activate': 'Activer',
        'plan.activating': 'Activation en cours...',
        'plan.activateSuccess': 'Activation réussie !',
        'plan.activateInvalid': 'Clé de licence invalide.',
        'plan.activateError': 'Erreur de connexion — veuillez réessayer.',
        'general.profile': 'Profil',
        'general.fullName': 'Nom complet',
        'general.preferredName': 'Comment NKTg AI doit-il vous appeler ?',
        'general.preferredNamePlaceholder': 'ex. un surnom...',
        'general.saved': 'Enregistré',
        'general.avatarChange': "Changer l'avatar",
        'general.avatarRemove': "Supprimer l'avatar",
        'general.avatarError': 'Impossible de charger cette image, essayez-en une autre.',
        'common.close': 'Fermer',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — prêt',
        'inputAdapter.success': '✔ {name} — {chars} caractères',
        'inputAdapter.unsupportedFormat': 'Format de fichier non pris en charge : .{ext}. Seuls .txt, .docx, .pdf, .png, .jpg, .webp, .bmp sont acceptés.',
        'inputAdapter.emptyContent': '{name} : Contenu vide après extraction.',
        'inputAdapter.exceedsLimit': '{name} : Dépasse {max} caractères (actuel : {current}). Veuillez raccourcir le contenu.',
        'inputAdapter.cannotReadTxt': 'Impossible de lire le fichier .txt',
        'inputAdapter.cannotReadDocx': 'Impossible de lire le fichier .docx',
        'inputAdapter.cannotReadPdf': 'Impossible de lire le fichier .pdf',
        'inputAdapter.mammothError': 'Erreur de traitement du document Word : {msg}',
        'inputAdapter.pdfError': 'Erreur de traitement du PDF : {msg}',
        'inputAdapter.canvasResizeFailed': "Échec du redimensionnement de l'image",
        'inputAdapter.cannotLoadImage': "Impossible de charger l'image pour le redimensionnement",
        'inputAdapter.ocrLoadFailed': 'Échec du chargement du moteur de reconnaissance de texte',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': 'Analyse',
        'step8.compression': 'Compression',
        'step8.expansion': 'Expansion',
        'step8.chars': 'Caractères',
        'step8.copy': '⎘ Copier',
        'step8.copied': '✓ Copié',
        'step8.copyTitle': 'Copier le résultat',
        'step8.condensedTitle': 'Lancer un cycle de compression supplémentaire',
        'step8.essenceTitle': 'Compression profonde, 4 cycles de plus (5 au total)',
        'step8.top': '↑ Haut',
        'step8.topTitle': 'Remonter en haut',
        'step8.proportionAxis': 'Proportion (%)',
        'step8.dominanceThreshold': 'Seuil de dominance',
        'step8.textStructure': 'Structure du texte (100%)',
        'step8.generalFormula': 'Formule générale : AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} entrées/jour',
        'plan.unlimited': 'Illimité',
        'plan.usageToday': "Aujourd'hui : {count}/{limit}",
        'plan.currentBadge': 'Actuel',
        'plan.comingSoon': 'Bientôt disponible',
        'plan.limitReached': "Vous avez atteint votre limite quotidienne d'entrées.",
        'plan.upgradeNow': 'Mettre à niveau',
        'vietqr.buyButton': 'Payer via VietQR',
        'vietqr.title': 'Payer via VietQR',
        'vietqr.creatingOrder': 'Création de la commande...',
        'vietqr.transferContent': 'Contenu du virement (à conserver tel quel) :',
        'vietqr.waiting': 'En attente du paiement...',
        'vietqr.success': '✓ Paiement réussi — activé !',
        'vietqr.error': "Une erreur s'est produite. Veuillez réessayer.",
        'plan.expiresOn': 'Renouvellement/expiration : {date}',
    },

    DE: {
        'nav.newChat': 'Neuer Chat',
        'nav.guide': 'Anleitung',
        'nav.signup': 'Registrieren / Anmelden',
        'nav.history': 'Verlauf',
        'history.empty': 'Noch kein Verlauf',
        'history.loginToView': 'Zum Anzeigen des Verlaufs anmelden',
        'history.shareConversation': 'Unterhaltung teilen',
        'history.unpin': 'Lösen',
        'history.pin': 'Anheften',
        'history.rename': 'Umbenennen',
        'history.delete': 'Löschen',
        'history.renamePlaceholder': 'Neuen Namen eingeben...',
        'history.shareLinkDesc': 'Öffentlicher Link, den Sie teilen können',
        'history.copy': 'Kopieren',
        'history.copied': '✓ Kopiert',
        'history.shareSocial': 'In sozialen Medien teilen',
        'history.deleteConfirm': 'Dieses Element aus dem Verlauf löschen?',
        'history.pinnedTooltip': 'Angeheftet',
        'history.optionsTooltip': 'Optionen',
        'history.clearAll': '🗑 Gesamten Verlauf löschen',
        'history.clearAllConfirm': 'Gesamten Verlauf löschen?',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ Bitte wählen Sie Extraction oder Addition, bevor Sie fortfahren.',
        'charLimit.warning': '⚠ Zeichenlimit von 21000 überschritten',
        'queryInput.placeholder': 'Text eingeben oder [+] klicken, um eine Datei anzuhängen (.txt, .docx, .pdf, .png, .jpg, .webp)...',
        'auth.title': 'NKTg-Konto',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'E-Mail',
        'auth.passwordPlaceholder': 'Passwort',
        'auth.loginBtn': 'Anmelden',
        'auth.noAccount': 'Noch kein Konto?',
        'auth.registerNow': 'Jetzt registrieren',
        'auth.fullNamePlaceholder': 'Vollständiger Name',
        'auth.passwordMinPlaceholder': 'Passwort (mind. 6 Zeichen)',
        'auth.confirmPasswordPlaceholder': 'Passwort bestätigen',
        'auth.registerBtn': 'Konto erstellen',
        'auth.haveAccount': 'Bereits ein Konto?',
        'auth.loginNow': 'Anmelden',
        'settings.title': 'Einstellungen',
        'settings.gearTitle': 'Einstellungen',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': 'Sie sind nicht angemeldet.',
        'account.login': 'Anmelden',
        'account.logout': 'Abmelden',
        'account.logoutConfirm': 'Möchten Sie sich abmelden?',
        'account.changePwd': 'Passwort ändern',
        'account.currentPwdPlaceholder': 'Aktuelles Passwort',
        'account.newPwdPlaceholder': 'Neues Passwort (mind. 6 Zeichen)',
        'account.confirmNewPwdPlaceholder': 'Neues Passwort bestätigen',
        'account.save': 'Speichern',
        'account.cancel': 'Abbrechen',
        'account.pwdMismatch': 'Passwortbestätigung stimmt nicht überein.',
        'account.deleteAccount': 'Konto löschen',
        'account.deleteWarning': 'Dies löscht Ihr Konto und den gesamten Verlauf <strong>in diesem Browser</strong> dauerhaft. Dies kann nicht rückgängig gemacht werden.',
        'account.deletePwdPlaceholder': 'Passwort zur Bestätigung eingeben',
        'account.deletePermanently': 'Endgültig löschen',
        'account.deleteWrongPwd': 'Falsches Passwort.',
        'account.deleteConfirmGoogle': 'Dieses Konto dauerhaft aus diesem Browser löschen? Der gesamte Verlauf wird gelöscht und kann nicht wiederhergestellt werden.',
        'changePwd.onlyEmail': 'Nur für Email-Konten verfügbar.',
        'changePwd.wrongCurrent': 'Das aktuelle Passwort ist falsch.',
        'changePwd.tooShort': 'Das neue Passwort muss mindestens 6 Zeichen haben.',
        'changePwd.success': 'Passwort erfolgreich geändert!',
        'plan.free': 'Free',
        'plan.licenseKey': 'Lizenzschlüssel',
        'plan.licensePlaceholder': 'Lizenzschlüssel nach dem Kauf hier einfügen...',
        'plan.licenseDisabled': 'Noch nicht verfügbar — Shop-Aktivierung ausstehend',
        'plan.activate': 'Aktivieren',
        'plan.activating': 'Wird aktiviert...',
        'plan.activateSuccess': 'Erfolgreich aktiviert!',
        'plan.activateInvalid': 'Ungültiger Lizenzschlüssel.',
        'plan.activateError': 'Verbindungsfehler — bitte erneut versuchen.',
        'general.profile': 'Profil',
        'general.fullName': 'Vollständiger Name',
        'general.preferredName': 'Wie soll NKTg AI Sie nennen?',
        'general.preferredNamePlaceholder': 'z. B. ein Spitzname...',
        'general.saved': 'Gespeichert',
        'general.avatarChange': 'Avatar ändern',
        'general.avatarRemove': 'Avatar entfernen',
        'general.avatarError': 'Dieses Bild konnte nicht hochgeladen werden, bitte ein anderes versuchen.',
        'common.close': 'Schließen',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — bereit',
        'inputAdapter.success': '✔ {name} — {chars} Zeichen',
        'inputAdapter.unsupportedFormat': 'Nicht unterstütztes Dateiformat: .{ext}. Nur .txt, .docx, .pdf, .png, .jpg, .webp, .bmp werden akzeptiert.',
        'inputAdapter.emptyContent': '{name}: Kein Inhalt nach der Extraktion.',
        'inputAdapter.exceedsLimit': '{name}: Überschreitet {max} Zeichen (aktuell: {current}). Bitte kürzen Sie den Inhalt.',
        'inputAdapter.cannotReadTxt': '.txt-Datei kann nicht gelesen werden',
        'inputAdapter.cannotReadDocx': '.docx-Datei kann nicht gelesen werden',
        'inputAdapter.cannotReadPdf': '.pdf-Datei kann nicht gelesen werden',
        'inputAdapter.mammothError': 'Fehler bei der Verarbeitung des Word-Dokuments: {msg}',
        'inputAdapter.pdfError': 'Fehler bei der PDF-Verarbeitung: {msg}',
        'inputAdapter.canvasResizeFailed': 'Bildgröße konnte nicht geändert werden',
        'inputAdapter.cannotLoadImage': 'Bild konnte zum Verkleinern nicht geladen werden',
        'inputAdapter.ocrLoadFailed': 'Texterkennungs-Engine konnte nicht geladen werden',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': 'Analyse',
        'step8.compression': 'Komprimierung',
        'step8.expansion': 'Erweiterung',
        'step8.chars': 'Zeichen',
        'step8.copy': '⎘ Kopieren',
        'step8.copied': '✓ Kopiert',
        'step8.copyTitle': 'Ergebnis kopieren',
        'step8.condensedTitle': 'Eine weitere Komprimierungsrunde ausführen',
        'step8.essenceTitle': '4 weitere Runden tief komprimieren (insgesamt 5)',
        'step8.top': '↑ Anfang',
        'step8.topTitle': 'Nach oben scrollen',
        'step8.proportionAxis': 'Anteil (%)',
        'step8.dominanceThreshold': 'Dominanzschwelle',
        'step8.textStructure': 'Textstruktur (100%)',
        'step8.generalFormula': 'Allgemeine Formel: AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} Eingaben/Tag',
        'plan.unlimited': 'Unbegrenzt',
        'plan.usageToday': 'Heute: {count}/{limit}',
        'plan.currentBadge': 'Aktuell',
        'plan.comingSoon': 'Demnächst',
        'plan.limitReached': 'Sie haben Ihr heutiges Eingabelimit erreicht.',
        'plan.upgradeNow': 'Upgrade',
        'vietqr.buyButton': 'Über VietQR bezahlen',
        'vietqr.title': 'Über VietQR bezahlen',
        'vietqr.creatingOrder': 'Bestellung wird erstellt...',
        'vietqr.transferContent': 'Verwendungszweck (genau so übernehmen):',
        'vietqr.waiting': 'Warten auf Zahlung...',
        'vietqr.success': '✓ Zahlung erfolgreich — aktiviert!',
        'vietqr.error': 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
        'plan.expiresOn': 'Verlängerung/Ablauf: {date}',
    },

    ES: {
        'nav.newChat': 'Nuevo chat',
        'nav.guide': 'Guía',
        'nav.signup': 'Registrarse / Iniciar sesión',
        'nav.history': 'Historial',
        'history.empty': 'Aún no hay historial',
        'history.loginToView': 'Inicia sesión para ver el historial',
        'history.shareConversation': 'Compartir conversación',
        'history.unpin': 'Desanclar',
        'history.pin': 'Anclar',
        'history.rename': 'Cambiar nombre',
        'history.delete': 'Eliminar',
        'history.renamePlaceholder': 'Introduce un nuevo nombre...',
        'history.shareLinkDesc': 'Enlace público que puedes compartir',
        'history.copy': 'Copiar',
        'history.copied': '✓ Copiado',
        'history.shareSocial': 'Compartir en redes sociales',
        'history.deleteConfirm': '¿Eliminar este elemento del historial?',
        'history.pinnedTooltip': 'Anclado',
        'history.optionsTooltip': 'Opciones',
        'history.clearAll': '🗑 Borrar todo el historial',
        'history.clearAllConfirm': '¿Borrar todo el historial?',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ Selecciona Extraction o Addition antes de ejecutar el proceso.',
        'charLimit.warning': '⚠ Límite de 21000 caracteres superado',
        'queryInput.placeholder': 'Escribe texto o haz clic en [+] para adjuntar un archivo (.txt, .docx, .pdf, .png, .jpg, .webp)...',
        'auth.title': 'Cuenta NKTg',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'Correo electrónico',
        'auth.passwordPlaceholder': 'Contraseña',
        'auth.loginBtn': 'Iniciar sesión',
        'auth.noAccount': '¿No tienes una cuenta?',
        'auth.registerNow': 'Regístrate ahora',
        'auth.fullNamePlaceholder': 'Nombre completo',
        'auth.passwordMinPlaceholder': 'Contraseña (mín. 6 caracteres)',
        'auth.confirmPasswordPlaceholder': 'Confirmar contraseña',
        'auth.registerBtn': 'Crear cuenta',
        'auth.haveAccount': '¿Ya tienes una cuenta?',
        'auth.loginNow': 'Iniciar sesión',
        'settings.title': 'Configuración',
        'settings.gearTitle': 'Configuración',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': 'No has iniciado sesión.',
        'account.login': 'Iniciar sesión',
        'account.logout': 'Cerrar sesión',
        'account.logoutConfirm': '¿Quieres cerrar sesión?',
        'account.changePwd': 'Cambiar contraseña',
        'account.currentPwdPlaceholder': 'Contraseña actual',
        'account.newPwdPlaceholder': 'Nueva contraseña (mín. 6 caracteres)',
        'account.confirmNewPwdPlaceholder': 'Confirmar nueva contraseña',
        'account.save': 'Guardar',
        'account.cancel': 'Cancelar',
        'account.pwdMismatch': 'La confirmación de contraseña no coincide.',
        'account.deleteAccount': 'Eliminar cuenta',
        'account.deleteWarning': 'Esto eliminará permanentemente tu cuenta y todo el historial <strong>en este navegador</strong>. No se puede deshacer.',
        'account.deletePwdPlaceholder': 'Ingresa tu contraseña para confirmar',
        'account.deletePermanently': 'Eliminar permanentemente',
        'account.deleteWrongPwd': 'Contraseña incorrecta.',
        'account.deleteConfirmGoogle': '¿Eliminar permanentemente esta cuenta de este navegador? Se eliminará todo el historial y no se puede deshacer.',
        'changePwd.onlyEmail': 'Solo disponible para cuentas de Email.',
        'changePwd.wrongCurrent': 'La contraseña actual es incorrecta.',
        'changePwd.tooShort': 'La nueva contraseña debe tener al menos 6 caracteres.',
        'changePwd.success': '¡Contraseña cambiada con éxito!',
        'plan.free': 'Free',
        'plan.licenseKey': 'Clave de licencia',
        'plan.licensePlaceholder': 'Pega tu clave de licencia después de comprar...',
        'plan.licenseDisabled': 'Aún no disponible — activación de la tienda pendiente',
        'plan.activate': 'Activar',
        'plan.activating': 'Activando...',
        'plan.activateSuccess': '¡Activado con éxito!',
        'plan.activateInvalid': 'Clave de licencia no válida.',
        'plan.activateError': 'Error de conexión — inténtalo de nuevo.',
        'general.profile': 'Perfil',
        'general.fullName': 'Nombre completo',
        'general.preferredName': '¿Cómo debería llamarte NKTg AI?',
        'general.preferredNamePlaceholder': 'p. ej. un apodo...',
        'general.saved': 'Guardado',
        'general.avatarChange': 'Cambiar avatar',
        'general.avatarRemove': 'Eliminar avatar',
        'general.avatarError': 'No se pudo subir esta imagen, prueba con otra.',
        'common.close': 'Cerrar',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — listo',
        'inputAdapter.success': '✔ {name} — {chars} caracteres',
        'inputAdapter.unsupportedFormat': 'Formato de archivo no compatible: .{ext}. Solo se aceptan .txt, .docx, .pdf, .png, .jpg, .webp, .bmp.',
        'inputAdapter.emptyContent': '{name}: Sin contenido después de la extracción.',
        'inputAdapter.exceedsLimit': '{name}: Supera los {max} caracteres (actual: {current}). Acorta el contenido.',
        'inputAdapter.cannotReadTxt': 'No se puede leer el archivo .txt',
        'inputAdapter.cannotReadDocx': 'No se puede leer el archivo .docx',
        'inputAdapter.cannotReadPdf': 'No se puede leer el archivo .pdf',
        'inputAdapter.mammothError': 'Error al procesar el documento Word: {msg}',
        'inputAdapter.pdfError': 'Error al procesar el PDF: {msg}',
        'inputAdapter.canvasResizeFailed': 'Error al redimensionar la imagen',
        'inputAdapter.cannotLoadImage': 'No se pudo cargar la imagen para redimensionar',
        'inputAdapter.ocrLoadFailed': 'No se pudo cargar el motor de reconocimiento de texto',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': 'Análisis',
        'step8.compression': 'Compresión',
        'step8.expansion': 'Expansión',
        'step8.chars': 'Caracteres',
        'step8.copy': '⎘ Copiar',
        'step8.copied': '✓ Copiado',
        'step8.copyTitle': 'Copiar resultado',
        'step8.condensedTitle': 'Ejecutar una ronda más de compresión',
        'step8.essenceTitle': 'Compresión profunda, 4 rondas más (5 en total)',
        'step8.top': '↑ Arriba',
        'step8.topTitle': 'Desplazarse arriba',
        'step8.proportionAxis': 'Proporción (%)',
        'step8.dominanceThreshold': 'Umbral de dominancia',
        'step8.textStructure': 'Estructura del texto (100%)',
        'step8.generalFormula': 'Fórmula general: AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} entradas/día',
        'plan.unlimited': 'Ilimitado',
        'plan.usageToday': 'Hoy: {count}/{limit}',
        'plan.currentBadge': 'Actual',
        'plan.comingSoon': 'Próximamente',
        'plan.limitReached': 'Has alcanzado tu límite diario de entradas.',
        'plan.upgradeNow': 'Mejorar',
        'vietqr.buyButton': 'Pagar con VietQR',
        'vietqr.title': 'Pagar con VietQR',
        'vietqr.creatingOrder': 'Creando pedido...',
        'vietqr.transferContent': 'Concepto de la transferencia (mantener igual):',
        'vietqr.waiting': 'Esperando el pago...',
        'vietqr.success': '✓ Pago exitoso — ¡activado!',
        'vietqr.error': 'Algo salió mal. Inténtalo de nuevo.',
        'plan.expiresOn': 'Renovación/vencimiento: {date}',
    },

    ZH: {
        'nav.newChat': '新建对话',
        'nav.guide': '指南',
        'nav.signup': '注册 / 登录',
        'nav.history': '历史记录',
        'history.empty': '暂无历史记录',
        'history.loginToView': '登录后查看历史记录',
        'history.shareConversation': '分享对话',
        'history.unpin': '取消置顶',
        'history.pin': '置顶',
        'history.rename': '重命名',
        'history.delete': '删除',
        'history.renamePlaceholder': '输入新名称...',
        'history.shareLinkDesc': '可分享的公开链接',
        'history.copy': '复制',
        'history.copied': '✓ 已复制',
        'history.shareSocial': '分享到社交媒体',
        'history.deleteConfirm': '从历史记录中删除此项？',
        'history.pinnedTooltip': '已置顶',
        'history.optionsTooltip': '选项',
        'history.clearAll': '🗑 清除全部历史记录',
        'history.clearAllConfirm': '清除全部历史记录？',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ 运行前请先选择 Extraction 或 Addition。',
        'charLimit.warning': '⚠ 已超过 21000 字符限制',
        'queryInput.placeholder': '输入文本，或点击 [+] 附加文件（.txt、.docx、.pdf、.png、.jpg、.webp）...',
        'auth.title': 'NKTg 账户',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': '邮箱',
        'auth.passwordPlaceholder': '密码',
        'auth.loginBtn': '登录',
        'auth.noAccount': '还没有账户？',
        'auth.registerNow': '立即注册',
        'auth.fullNamePlaceholder': '姓名',
        'auth.passwordMinPlaceholder': '密码（至少 6 个字符）',
        'auth.confirmPasswordPlaceholder': '确认密码',
        'auth.registerBtn': '创建账户',
        'auth.haveAccount': '已有账户？',
        'auth.loginNow': '登录',
        'settings.title': '设置',
        'settings.gearTitle': '设置',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': '您尚未登录。',
        'account.login': '登录',
        'account.logout': '退出登录',
        'account.logoutConfirm': '确定要退出登录吗？',
        'account.changePwd': '修改密码',
        'account.currentPwdPlaceholder': '当前密码',
        'account.newPwdPlaceholder': '新密码（至少 6 个字符）',
        'account.confirmNewPwdPlaceholder': '确认新密码',
        'account.save': '保存',
        'account.cancel': '取消',
        'account.pwdMismatch': '两次输入的密码不一致。',
        'account.deleteAccount': '删除账户',
        'account.deleteWarning': '此操作将永久删除您<strong>在此浏览器上</strong>的账户和全部历史记录，且无法撤销。',
        'account.deletePwdPlaceholder': '输入密码以确认',
        'account.deletePermanently': '永久删除',
        'account.deleteWrongPwd': '密码不正确。',
        'account.deleteConfirmGoogle': '确定要从此浏览器永久删除该账户吗？所有历史记录都将被删除，且无法恢复。',
        'changePwd.onlyEmail': '仅适用于邮箱账户。',
        'changePwd.wrongCurrent': '当前密码不正确。',
        'changePwd.tooShort': '新密码至少需要 6 个字符。',
        'changePwd.success': '密码修改成功！',
        'plan.free': 'Free',
        'plan.licenseKey': '许可证密钥',
        'plan.licensePlaceholder': '购买后将许可证密钥粘贴于此...',
        'plan.licenseDisabled': '暂未开放 — 商店激活中',
        'plan.activate': '激活',
        'plan.activating': '正在激活...',
        'plan.activateSuccess': '激活成功！',
        'plan.activateInvalid': '许可证密钥无效。',
        'plan.activateError': '连接错误 — 请重试。',
        'general.profile': '个人资料',
        'general.fullName': '姓名',
        'general.preferredName': '希望 NKTg AI 怎么称呼您？',
        'general.preferredNamePlaceholder': '例如：昵称...',
        'general.saved': '已保存',
        'general.avatarChange': '更换头像',
        'general.avatarRemove': '移除头像',
        'general.avatarError': '无法上传此图片，请尝试其他图片。',
        'common.close': '关闭',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — 已就绪',
        'inputAdapter.success': '✔ {name} — {chars} 字符',
        'inputAdapter.unsupportedFormat': '不支持的文件格式：.{ext}。仅支持 .txt、.docx、.pdf、.png、.jpg、.webp、.bmp。',
        'inputAdapter.emptyContent': '{name}：提取后内容为空。',
        'inputAdapter.exceedsLimit': '{name}：超过 {max} 字符限制（当前：{current}）。请缩短内容。',
        'inputAdapter.cannotReadTxt': '无法读取 .txt 文件',
        'inputAdapter.cannotReadDocx': '无法读取 .docx 文件',
        'inputAdapter.cannotReadPdf': '无法读取 .pdf 文件',
        'inputAdapter.mammothError': 'Word 文档处理错误：{msg}',
        'inputAdapter.pdfError': 'PDF 处理错误：{msg}',
        'inputAdapter.canvasResizeFailed': '图片缩放失败',
        'inputAdapter.cannotLoadImage': '无法加载图片以进行缩放',
        'inputAdapter.ocrLoadFailed': '文字识别引擎加载失败',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': '分析',
        'step8.compression': '压缩',
        'step8.expansion': '扩展',
        'step8.chars': '字符',
        'step8.copy': '⎘ 复制',
        'step8.copied': '✓ 已复制',
        'step8.copyTitle': '复制结果',
        'step8.condensedTitle': '再运行一轮压缩',
        'step8.essenceTitle': '深度压缩再进行4轮（共5轮）',
        'step8.top': '↑ 顶部',
        'step8.topTitle': '滚动到顶部',
        'step8.proportionAxis': '占比 (%)',
        'step8.dominanceThreshold': '优势阈值',
        'step8.textStructure': '文本结构 (100%)',
        'step8.generalFormula': '通用公式：AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} 次/天',
        'plan.unlimited': '无限制',
        'plan.usageToday': '今日：{count}/{limit}',
        'plan.currentBadge': '当前方案',
        'plan.comingSoon': '即将推出',
        'plan.limitReached': '您今天的输入次数已用完。',
        'plan.upgradeNow': '升级',
        'vietqr.buyButton': '通过 VietQR 支付',
        'vietqr.title': '通过 VietQR 支付',
        'vietqr.creatingOrder': '正在创建订单...',
        'vietqr.transferContent': '转账内容（请保持不变）：',
        'vietqr.waiting': '等待付款中...',
        'vietqr.success': '✓ 支付成功 — 已激活！',
        'vietqr.error': '出错了，请重试。',
        'plan.expiresOn': '续费/到期日：{date}',
    },

    JA: {
        'nav.newChat': '新しいチャット',
        'nav.guide': 'ガイド',
        'nav.signup': '新規登録 / ログイン',
        'nav.history': '履歴',
        'history.empty': 'まだ履歴がありません',
        'history.loginToView': '履歴を見るにはログインしてください',
        'history.shareConversation': '会話を共有',
        'history.unpin': 'ピン留め解除',
        'history.pin': 'ピン留め',
        'history.rename': '名前を変更',
        'history.delete': '削除',
        'history.renamePlaceholder': '新しい名前を入力...',
        'history.shareLinkDesc': '共有できる公開リンク',
        'history.copy': 'コピー',
        'history.copied': '✓ コピーしました',
        'history.shareSocial': 'SNSで共有',
        'history.deleteConfirm': 'この項目を履歴から削除しますか？',
        'history.pinnedTooltip': 'ピン留め済み',
        'history.optionsTooltip': 'オプション',
        'history.clearAll': '🗑 履歴をすべて削除',
        'history.clearAllConfirm': '履歴をすべて削除しますか？',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ 実行前に Extraction または Addition を選択してください。',
        'charLimit.warning': '⚠ 21000文字の上限を超えています',
        'queryInput.placeholder': 'テキストを入力するか、[+] をクリックしてファイルを添付（.txt, .docx, .pdf, .png, .jpg, .webp）...',
        'auth.title': 'NKTg アカウント',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'メールアドレス',
        'auth.passwordPlaceholder': 'パスワード',
        'auth.loginBtn': 'ログイン',
        'auth.noAccount': 'アカウントをお持ちでないですか？',
        'auth.registerNow': '今すぐ登録',
        'auth.fullNamePlaceholder': '氏名',
        'auth.passwordMinPlaceholder': 'パスワード（6文字以上）',
        'auth.confirmPasswordPlaceholder': 'パスワードの確認',
        'auth.registerBtn': 'アカウントを作成',
        'auth.haveAccount': 'すでにアカウントをお持ちですか？',
        'auth.loginNow': 'ログイン',
        'settings.title': '設定',
        'settings.gearTitle': '設定',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': 'ログインしていません。',
        'account.login': 'ログイン',
        'account.logout': 'ログアウト',
        'account.logoutConfirm': 'ログアウトしますか？',
        'account.changePwd': 'パスワードを変更',
        'account.currentPwdPlaceholder': '現在のパスワード',
        'account.newPwdPlaceholder': '新しいパスワード（6文字以上）',
        'account.confirmNewPwdPlaceholder': '新しいパスワードの確認',
        'account.save': '保存',
        'account.cancel': 'キャンセル',
        'account.pwdMismatch': '確認用パスワードが一致しません。',
        'account.deleteAccount': 'アカウントを削除',
        'account.deleteWarning': 'この操作は<strong>このブラウザ上</strong>のアカウントと全履歴を完全に削除します。元に戻せません。',
        'account.deletePwdPlaceholder': '確認のためパスワードを入力',
        'account.deletePermanently': '完全に削除',
        'account.deleteWrongPwd': 'パスワードが正しくありません。',
        'account.deleteConfirmGoogle': 'このブラウザからこのアカウントを完全に削除しますか？全履歴が削除され、元に戻せません。',
        'changePwd.onlyEmail': 'Emailアカウントのみ利用できます。',
        'changePwd.wrongCurrent': '現在のパスワードが正しくありません。',
        'changePwd.tooShort': '新しいパスワードは6文字以上にしてください。',
        'changePwd.success': 'パスワードを変更しました！',
        'plan.free': 'Free',
        'plan.licenseKey': 'ライセンスキー',
        'plan.licensePlaceholder': '購入後、ライセンスキーをここに貼り付けてください...',
        'plan.licenseDisabled': 'まだ利用できません — ストア有効化待ち',
        'plan.activate': '有効化',
        'plan.activating': '有効化中...',
        'plan.activateSuccess': '有効化に成功しました！',
        'plan.activateInvalid': 'ライセンスキーが無効です。',
        'plan.activateError': '接続エラー — もう一度お試しください。',
        'general.profile': 'プロフィール',
        'general.fullName': '氏名',
        'general.preferredName': 'NKTg AI にどう呼ばれたいですか？',
        'general.preferredNamePlaceholder': '例：ニックネーム...',
        'general.saved': '保存しました',
        'general.avatarChange': 'アバターを変更',
        'general.avatarRemove': 'アバターを削除',
        'general.avatarError': 'この画像はアップロードできませんでした。別の画像をお試しください。',
        'common.close': '閉じる',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — 準備完了',
        'inputAdapter.success': '✔ {name} — {chars} 文字',
        'inputAdapter.unsupportedFormat': 'サポートされていないファイル形式です：.{ext}。.txt、.docx、.pdf、.png、.jpg、.webp、.bmp のみ対応しています。',
        'inputAdapter.emptyContent': '{name}：抽出後のコンテンツが空です。',
        'inputAdapter.exceedsLimit': '{name}：{max} 文字を超えています（現在：{current}）。内容を短くしてください。',
        'inputAdapter.cannotReadTxt': '.txt ファイルを読み込めません',
        'inputAdapter.cannotReadDocx': '.docx ファイルを読み込めません',
        'inputAdapter.cannotReadPdf': '.pdf ファイルを読み込めません',
        'inputAdapter.mammothError': 'Word文書の処理エラー：{msg}',
        'inputAdapter.pdfError': 'PDF処理エラー：{msg}',
        'inputAdapter.canvasResizeFailed': '画像のリサイズに失敗しました',
        'inputAdapter.cannotLoadImage': 'リサイズ用の画像を読み込めません',
        'inputAdapter.ocrLoadFailed': '文字認識エンジンの読み込みに失敗しました',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': '分析',
        'step8.compression': '圧縮',
        'step8.expansion': '拡張',
        'step8.chars': '文字数',
        'step8.copy': '⎘ コピー',
        'step8.copied': '✓ コピーしました',
        'step8.copyTitle': '結果をコピー',
        'step8.condensedTitle': '圧縮をもう1ラウンド実行',
        'step8.essenceTitle': 'さらに4ラウンド深く圧縮（計5ラウンド）',
        'step8.top': '↑ トップ',
        'step8.topTitle': 'トップへ戻る',
        'step8.proportionAxis': '割合 (%)',
        'step8.dominanceThreshold': '優勢しきい値',
        'step8.textStructure': 'テキスト構造 (100%)',
        'step8.generalFormula': '一般式：AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} 回/日',
        'plan.unlimited': '無制限',
        'plan.usageToday': '本日：{count}/{limit}',
        'plan.currentBadge': '現在のプラン',
        'plan.comingSoon': '近日公開',
        'plan.limitReached': '本日の入力上限に達しました。',
        'plan.upgradeNow': 'アップグレード',
        'vietqr.buyButton': 'VietQRで支払う',
        'vietqr.title': 'VietQRで支払う',
        'vietqr.creatingOrder': '注文を作成中...',
        'vietqr.transferContent': '振込内容（そのまま使用してください）：',
        'vietqr.waiting': '支払いを待っています...',
        'vietqr.success': '✓ 支払い完了 — 有効化されました！',
        'vietqr.error': 'エラーが発生しました。もう一度お試しください。',
        'plan.expiresOn': '更新/期限: {date}',
    },

    RU: {
        'nav.newChat': 'Новый чат',
        'nav.guide': 'Гид',
        'nav.signup': 'Регистрация / Вход',
        'nav.history': 'История',
        'history.empty': 'Истории пока нет',
        'history.loginToView': 'Войдите, чтобы увидеть историю',
        'history.shareConversation': 'Поделиться разговором',
        'history.unpin': 'Открепить',
        'history.pin': 'Закрепить',
        'history.rename': 'Переименовать',
        'history.delete': 'Удалить',
        'history.renamePlaceholder': 'Введите новое имя...',
        'history.shareLinkDesc': 'Публичная ссылка, которой можно поделиться',
        'history.copy': 'Копировать',
        'history.copied': '✓ Скопировано',
        'history.shareSocial': 'Поделиться в соцсетях',
        'history.deleteConfirm': 'Удалить этот элемент из истории?',
        'history.pinnedTooltip': 'Закреплено',
        'history.optionsTooltip': 'Параметры',
        'history.clearAll': '🗑 Очистить всю историю',
        'history.clearAllConfirm': 'Очистить всю историю?',
        'mode.extraction': 'Extraction',
        'mode.addition': 'Addition',
        'mode.warning': '⚠ Пожалуйста, выберите Extraction или Addition перед запуском.',
        'charLimit.warning': '⚠ Превышен лимит в 21000 символов',
        'queryInput.placeholder': 'Введите текст или нажмите [+], чтобы прикрепить файл (.txt, .docx, .pdf, .png, .jpg, .webp)...',
        'auth.title': 'Аккаунт NKTg',
        'auth.tabEmail': 'Email',
        'auth.tabGoogle': 'Google',
        'auth.emailPlaceholder': 'Email',
        'auth.passwordPlaceholder': 'Пароль',
        'auth.loginBtn': 'Войти',
        'auth.noAccount': 'Нет аккаунта?',
        'auth.registerNow': 'Зарегистрироваться',
        'auth.fullNamePlaceholder': 'Полное имя',
        'auth.passwordMinPlaceholder': 'Пароль (мин. 6 символов)',
        'auth.confirmPasswordPlaceholder': 'Подтвердите пароль',
        'auth.registerBtn': 'Создать аккаунт',
        'auth.haveAccount': 'Уже есть аккаунт?',
        'auth.loginNow': 'Войти',
        'settings.title': 'Настройки',
        'settings.gearTitle': 'Настройки',
        'settings.tabGeneral': 'General',
        'settings.tabAccount': 'Account',
        'settings.tabPlan': 'Plan',
        'settings.tabLanguage': 'Language',
        'account.notLoggedIn': 'Вы не вошли в систему.',
        'account.login': 'Войти',
        'account.logout': 'Выйти',
        'account.logoutConfirm': 'Вы хотите выйти?',
        'account.changePwd': 'Изменить пароль',
        'account.currentPwdPlaceholder': 'Текущий пароль',
        'account.newPwdPlaceholder': 'Новый пароль (мин. 6 символов)',
        'account.confirmNewPwdPlaceholder': 'Подтвердите новый пароль',
        'account.save': 'Сохранить',
        'account.cancel': 'Отмена',
        'account.pwdMismatch': 'Пароли не совпадают.',
        'account.deleteAccount': 'Удалить аккаунт',
        'account.deleteWarning': 'Это безвозвратно удалит ваш аккаунт и всю историю <strong>на этом браузере</strong>. Действие нельзя отменить.',
        'account.deletePwdPlaceholder': 'Введите пароль для подтверждения',
        'account.deletePermanently': 'Удалить навсегда',
        'account.deleteWrongPwd': 'Неверный пароль.',
        'account.deleteConfirmGoogle': 'Безвозвратно удалить этот аккаунт с этого браузера? Вся история будет удалена без возможности восстановления.',
        'changePwd.onlyEmail': 'Доступно только для Email-аккаунтов.',
        'changePwd.wrongCurrent': 'Текущий пароль неверен.',
        'changePwd.tooShort': 'Новый пароль должен содержать не менее 6 символов.',
        'changePwd.success': 'Пароль успешно изменён!',
        'plan.free': 'Free',
        'plan.licenseKey': 'Лицензионный ключ',
        'plan.licensePlaceholder': 'Вставьте лицензионный ключ после покупки...',
        'plan.licenseDisabled': 'Пока недоступно — ожидается активация магазина',
        'plan.activate': 'Активировать',
        'plan.activating': 'Активация...',
        'plan.activateSuccess': 'Успешно активировано!',
        'plan.activateInvalid': 'Неверный лицензионный ключ.',
        'plan.activateError': 'Ошибка соединения — попробуйте снова.',
        'general.profile': 'Профиль',
        'general.fullName': 'Полное имя',
        'general.preferredName': 'Как NKTg AI должен вас называть?',
        'general.preferredNamePlaceholder': 'напр. прозвище...',
        'general.saved': 'Сохранено',
        'general.avatarChange': 'Изменить аватар',
        'general.avatarRemove': 'Удалить аватар',
        'general.avatarError': 'Не удалось загрузить это изображение, попробуйте другое.',
        'common.close': 'Закрыть',
        'pipeline.label': 'PIPELINE',
        'inputAdapter.ready': '📄 {name} — готово',
        'inputAdapter.success': '✔ {name} — {chars} симв.',
        'inputAdapter.unsupportedFormat': 'Неподдерживаемый формат файла: .{ext}. Принимаются только .txt, .docx, .pdf, .png, .jpg, .webp, .bmp.',
        'inputAdapter.emptyContent': '{name}: Пустое содержимое после извлечения.',
        'inputAdapter.exceedsLimit': '{name}: Превышает {max} символов (текущее: {current}). Сократите содержимое.',
        'inputAdapter.cannotReadTxt': 'Не удаётся прочитать файл .txt',
        'inputAdapter.cannotReadDocx': 'Не удаётся прочитать файл .docx',
        'inputAdapter.cannotReadPdf': 'Не удаётся прочитать файл .pdf',
        'inputAdapter.mammothError': 'Ошибка обработки документа Word: {msg}',
        'inputAdapter.pdfError': 'Ошибка обработки PDF: {msg}',
        'inputAdapter.canvasResizeFailed': 'Не удалось изменить размер изображения',
        'inputAdapter.cannotLoadImage': 'Не удалось загрузить изображение для изменения размера',
        'inputAdapter.ocrLoadFailed': 'Не удалось загрузить движок распознавания текста',
        'step8.titleExtraction': 'NKTg Extraction',
        'step8.titleAddition': 'NKTg Addition',
        'step8.analysis': 'Анализ',
        'step8.compression': 'Сжатие',
        'step8.expansion': 'Расширение',
        'step8.chars': 'Символы',
        'step8.copy': '⎘ Копировать',
        'step8.copied': '✓ Скопировано',
        'step8.copyTitle': 'Копировать результат',
        'step8.condensedTitle': 'Запустить ещё один раунд сжатия',
        'step8.essenceTitle': 'Глубокое сжатие ещё 4 раунда (всего 5)',
        'step8.top': '↑ Наверх',
        'step8.topTitle': 'Прокрутить наверх',
        'step8.proportionAxis': 'Доля (%)',
        'step8.dominanceThreshold': 'Порог доминирования',
        'step8.textStructure': 'Структура текста (100%)',
        'step8.generalFormula': 'Общая формула: AMP + DAMP + STABLE = 100%',
        'plan.dailyLimit': '{limit} запросов/день',
        'plan.unlimited': 'Без ограничений',
        'plan.usageToday': 'Сегодня: {count}/{limit}',
        'plan.currentBadge': 'Текущий',
        'plan.comingSoon': 'Скоро',
        'plan.limitReached': 'Вы достигли дневного лимита ввода.',
        'plan.upgradeNow': 'Улучшить',
        'vietqr.buyButton': 'Оплатить через VietQR',
        'vietqr.title': 'Оплатить через VietQR',
        'vietqr.creatingOrder': 'Создание заказа...',
        'vietqr.transferContent': 'Назначение платежа (оставить как есть):',
        'vietqr.waiting': 'Ожидание оплаты...',
        'vietqr.success': '✓ Оплата прошла успешно — активировано!',
        'vietqr.error': 'Что-то пошло не так. Попробуйте снова.',
        'plan.expiresOn': 'Продление/срок действия: {date}',
    },
};

// ============================================================================
// CORE — t() / setLang() / getLang() / applyStaticTranslations()
// ============================================================================

let currentLang = localStorage.getItem(LANG_STORAGE_KEY) || DEFAULT_LANG;
if (!TRANSLATIONS[currentLang]) currentLang = DEFAULT_LANG;

export function t(key, params) {
    let str = (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key])
        || TRANSLATIONS[DEFAULT_LANG][key]
        || key;
    if (params) {
        Object.keys(params).forEach(k => {
            str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), params[k]);
        });
    }
    return str;
}

export function getLang() {
    return currentLang;
}

export function applyStaticTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const val = t(el.dataset.i18n);
        if (val) el.textContent = val;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const val = t(el.dataset.i18nPlaceholder);
        if (val) el.placeholder = val;
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const val = t(el.dataset.i18nTitle);
        if (val) el.title = val;
    });
    document.documentElement.lang = currentLang.toLowerCase();
}

export function setLang(code) {
    if (!TRANSLATIONS[code]) return;
    currentLang = code;
    localStorage.setItem(LANG_STORAGE_KEY, code);
    applyStaticTranslations();
    document.dispatchEvent(new CustomEvent('nktg:langchange', { detail: { lang: code } }));
}

// ============================================================================
// TAB: LANGUAGE (trong Settings modal)
// ============================================================================

export function renderLanguageTab() {
    const container = document.getElementById('settingsLanguageContent');
    if (!container) return;

    const items = Object.keys(LANGS).map(code => `
        <button class="settings-row-btn" data-lang-option="${code}" style="display:flex;align-items:center;gap:10px;${code === currentLang ? 'border-color:var(--accent-color);background:#fff7ed;color:var(--accent-color);font-weight:600;' : ''}">
            <span style="font-size:18px;line-height:1;">${LANGS[code].flag}</span>
            <span>${LANGS[code].label}</span>
        </button>
    `).join('');

    container.innerHTML = `<div class="settings-field-label" style="margin-bottom:14px;">${t('settings.tabLanguage')}</div>${items}`;

    container.querySelectorAll('[data-lang-option]').forEach(btn => {
        btn.addEventListener('click', () => {
            setLang(btn.dataset.langOption);
            renderLanguageTab();
        });
    });
}

// ============================================================================
// EXPORT — window.* để settings.js / auth.js / history-manager.js dùng chung
// ============================================================================
window._nktgLanguage = { t, setLang, getLang, applyStaticTranslations, renderLanguageTab, LANGS };

// ============================================================================
// INIT — áp dụng ngôn ngữ đã lưu (hoặc mặc định EN) ngay khi DOM sẵn sàng
// ============================================================================
function initLanguage() {
    applyStaticTranslations();
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initLanguage);
} else {
    initLanguage();
}
